#Function to convert any model with reversible reactions to a copy of the same m-
#-odel with only irreversible reactions. ID of reverse reactions are generated by 
#suffixing "_reverse" to the ID of the orignal reaction.
#args: 1) a cobra model
#output: a cobra model with only irreversible reactions
def rev2irrev(cobra_model):
  exp_model=cobra_model.copy()
  
  for RXN in cobra_model.reactions:
    rxn=exp_model.reactions.get_by_id(RXN.id)
    if (rxn.lower_bound < 0):
      rxn_reverse = rxn.copy()
      rxn_reverse.id = "%s_reverse" %(rxn.id)
      rxn.lower_bound = 0
      rxn_reverse.upper_bound = 0
      exp_model.add_reaction(rxn_reverse)
  
  return exp_model

